### ISSUE TITLE
Adding in a new criteria for harassing behavior?

### ISSUE THREAD

**Issue by amandaharlin** [techlahoma/CodeofConduct#8]
What do y'all think about adding in points to cover 

- [ ]  unwelcome physical contact (not sexual, not inappropriate, but very not ok)   
(jsconf in their opening announcements made a point to remind everyone to ask before you touch someone, ask before you hug. that really stuck with me. when  we met hackygolucky irl i asked if i could hug her and she said yes. it felt great knowing i hadn't overstepped physical bounds by asking first.) 
- [ ]  if a question or comment could be interpreted as rude, mean, or otherwise not conducive to building a community, don't say it. 
- [ ]  adding "gender identity" instead of just "gender"? 
(confcodeofconduct has a gr8 sentence: gender, gender identity and expression, age, sexual orientation, disability, physical appearance, body size, race, or religion (or lack thereof))

what am i forgetting or leaving out?

**Comment by the-simian** [comment]
these seem reasonable, Put them into the CoC you're composing, in your own words, and I'll update the site also.
